cluster: "pbs-submit.py "
cluster-status: "pbs-status.py"
jobscript: "pbs-jobscript.sh"
jobs: 5000
immediate-submit: False
verbose: True
notemp: True
rerun-incomplete: True
keep-going: True
latency-wait: 10
max-jobs-per-second: 1
restart-times: 1
